routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// public
Route::get('/', 'HomeController@index')
    ->name('home');
Route::get('/profiles', 'MenuController@profiles')
    ->name('profiles');
Route::get('/berita', 'MenuController@berita')
    ->name('berita');
Route::get('/berita/ustyanto', 'MenuController@ustyanto')
    ->name('detail.ustyanto');
Route::get('/berita/beting-to-bening', 'MenuController@beting_to_bening')
    ->name('detail.beting_to_bening');
Route::get('/berita/training-imam-dan-khatib', 'MenuController@training_imam_dan_khatib')
    ->name('detail.training_imam_dan_khatib');
Route::get('/gambar', 'MenuController@gambar')
    ->name('gambar');
Route::get('/kontak', 'MenuController@kontak')
    ->name('kontak');
Route::post('/kontak/store', 'MenuController@store');
Route::post('/kontak/stores', 'MenuController@stores');

// admin & dai
Route::group(['middleware' => 'auth'], function () {

    Route::get('/kegiatan', 'KegiatanController@input')
        ->name('kegiatan_input');;

    Route::post('/kegiatan/store', 'KegiatanController@store');

    Route::get('kegiatan/export-excel/', 'KegiatanController@export_excel');

    Route::resource(
        'kegiatans',
        'KegiatanController',
        ['except' => ['create']]
    );

    Route::get('/mualaf', 'MualafController@input')
        ->name('mualaf');

    Route::post('/mualaf/create', 'MualafController@create');

    Route::resource(
        'mualafs',
        'MualafController',
        ['except' => ['create']]
    );

    Route::get('mualaf/export-excel/', 'MualafController@export_excel');

    Route::get('/getDistricts/{id}', 'KegiatanController@getDistricts');

    Route::get('/getVillages/{id}', 'KegiatanController@getVillages');

    Route::get('/profile', 'ProfileController@edit')
        ->name('profile.edit');

    Route::patch('/profile', 'ProfileController@update')
        ->name('profile.update');

    Route::get('password', 'PasswordController@edit')
        ->name('user.password.edit');

    Route::patch('password', 'PasswordController@update')
        ->name('user.password.update');

    Route::get('dashboard', 'DashboardController@index')
        ->name('dashboard.index');
});

// admin
Route::prefix('admin')
    ->namespace('Admin')
    ->middleware(['auth', 'admin'])
    ->group(function () {
        Route::resource('users', 'UsersController');
        Route::resource('pesan', 'PesanController');
        Route::get('dai', 'UsersController@dai')
            ->name('dai.index');

        Route::get('/dai/create-dai', 'UsersController@create_dai')
            ->name('dai.create_dai');;
        Route::post('/dai/store-dai', 'UsersController@store_dai')->name('dai.store_dai');

        Route::get('/dai/{user}/ubah', 'UsersController@ubah')->name('dai.ubah');
        Route::put('/dai/simpan/{user}', 'UsersController@simpan')->name('dai.simpan');
        Route::get('/dai/detail/{user}', 'UsersController@detail')->name('dai.detail');
        Route::delete('/dai/delete/{user}', 'UsersController@delete')->name('dai.delete');

        Route::resource('role', 'RoleController');
    });

Auth::routes(['verify' => true]);

app/Mualaf.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Mualaf extends Model
{
    // use SoftDeletes;

    protected $fillable = [
        'jml_mualaf', 'tgl', 'users_id', 'date', 'month', 'year'
    ];

    // 'alamat', 'id_kab', 'id_kec', 'id_desa',

    // protected $hidden = [];

    public function user()
    {
        return $this->belongsTo(User::class, 'users_id', 'id');
    }

    // public function kab()
    // {
    //     return $this->belongsTo(Reg_regencies::class, 'id_kab', 'id');
    // }

    // public function kec()
    // {
    //     return $this->belongsTo(Reg_districts::class, 'id_kec', 'id');
    // }

    // public function desa()
    // {
    //     return $this->belongsTo(Reg_villages::class, 'id_desa', 'id');
    // }

    public function fotos()
    {
        return $this->hasMany(MualafDetail::class, 'mualafs_id', 'id');
    }
}

app/Http/Controllers/MualafController.php
<?php

namespace App\Http\Controllers;

use App\Mualaf;
use App\MualafDetails;
use App\Http\Controllers\Controller;
use App\MualafDetail;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;
use App\Reg_regencies;
use App\Reg_districts;
use App\Reg_villages;
use App\User;
use Illuminate\Support\Facades\DB;

use App\Exports\MualafsExport;
use Maatwebsite\Excel\Facades\Excel;


class MualafController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    // bagian CMS
    public function index()
    {
        $user_id = Auth::user()->role_id;
        if ($user_id == 1) {
            $items = Mualaf::with([
                'user'
            ])->get();
            return view('pages.cms.mualaf.index', [
                'items' => $items
            ]);
        } elseif ($user_id == 2) {
            $items = Mualaf::with([
                'user'
            ])->where('users_id', '=', Auth::user()->id)
                ->get();
            return view('pages.cms.mualaf.index', [
                'items' => $items
            ]);
        }
    }

    public function show(Mualaf $mualaf)
    {
        $user = User::all();
        $mualafs = MualafDetail::all();

        return view('pages.cms.mualaf.detail', [
            'mualaf' => $mualaf,
            'mualafs' => $mualafs,
            'user' => $user
        ]);
    }

    public function edit(Mualaf $mualaf)
    {
        $user_id = Auth::user()->role_id;
        if ($user_id == 1) {
            $user = User::all();
            $mualafs = MualafDetail::all();

            return view('pages.cms.mualaf.edit', [
                'mualaf' => $mualaf,
                'user' => $user,
                'mualafs' => $mualafs
            ]);
        } else {
            return abort(404);
        }
    }

    public function update(Request $request, Mualaf $mualaf)
    {
        $this->validate($request, [
            'tgl' => 'required',
            'jml_mualaf' => 'required|numeric'
        ]);

        $mualaf->update([
            'tgl' => $request->tgl,
            'jml_mualaf' => $request->jml_mualaf,
        ]);

        $this->validate($request, [
            'foto.*' => 'mimes:jpeg,jpg,png|max:2000',
            'nama' => 'required',
            'alamat' => 'required',
            'deskripsi' => 'required'
        ]);

        if ($request->file("foto") == null) {
            if (count($request->id) > 0) {
                foreach ($request->id as $item => $v) {
                    $datad = array(
                        'nama' => $request->nama[$item],
                        'alamat' => $request->alamat[$item],
                        'deskripsi' => $request->deskripsi[$item],
                    );
                    $dbazar = MualafDetail::where('id', $request->id[$item])->first();
                    $dbazar->update($datad);
                }
                session()->flash('sukses', 'Data Mualaf berhasil edit');
                return redirect(route('mualafs.index'));
            }
        }

        if (count($request->file('foto')) > 0) {
            foreach ($request->file('foto') as $item => $v) {
                $datad = array(
                    'nama' => $request->nama[$item],
                    'alamat' => $request->alamat[$item],
                    'deskripsi' => $request->deskripsi[$item],
                    'foto' => $v->getClientOriginalName()
                );
                $v->storeAs('public/mualaf', $v->getClientOriginalName());
                $dbazar = MualafDetail::where('id', $request->id[$item])->first();
                $dbazar->update($datad);
            }
            session()->flash('sukses', 'Data Mualaf berhasil edit');
            return redirect(route('mualafs.index'));
        }

        // $images = MualafDetail::where("foto", $request->foto)->get();
        // dd($images);
        // if (count($request->file('foto')) > 0) {
        //     foreach ($request->file('foto') as $item => $v) {
        //         dd($images);
        //         foreach ($images as $image) {
        //             if (File::exists("storage/mualaf/" . $image->foto)) {
        //                 File::delete("storage/mualaf/" . $image->foto);
        //             }
        //             // dd($image->foto);
        //             $datad = array(
        //                 'nama' => $request->nama[$item],
        //                 'alamat' => $request->alamat[$item],
        //                 'deskripsi' => $request->deskripsi[$item],
        //                 'foto' => $v->getClientOriginalName()
        //             );
        //             $v->storeAs('public/mualaf', $v->getClientOriginalName());
        //             $dbazar = MualafDetail::where('id', $request->id[$item])->first();
        //             $dbazar->update($datad);
        //         }
        //     }
        //     session()->flash('sukses', 'Data Mualaf berhasil edit');
        //     return redirect(route('mualafs.index'));
        // }
    }

    public function destroy(Mualaf $mualaf)
    {
        $user_id = Auth::user()->role_id;
        if ($user_id == 1) {
            $images = MualafDetail::where("mualafs_id", $mualaf->id)->get();
            foreach ($images as $image) {
                if (File::exists("storage/mualaf/" . $image->foto)) {
                    File::delete("storage/mualaf/" . $image->foto);
                }
            }
            $mualaf->delete();
            $mualaf->fotos()->delete();
            session()->flash('sukses', 'Data berhasil dihapus');
            return redirect()->route('mualafs.index');
        } else {
            return abort(404);
        }
    }

    public function export_excel()
    {
        return Excel::download(new MualafsExport, 'Data Mualaf 2021.xlsx');
    }

    // bagian LMS
    public function input(Request $request)
    {
        $daiData['data'] = User::orderby("username", "asc")
            ->select('id', 'username')
            ->get();

        return view('pages.mualaf.index', compact('daiData'));
    }

    public function create(Request $request)
    {
        $expiry = explode("/", $request->tgl);

        $date = $expiry[0];
        $month = $expiry[1];
        $year = $expiry[2];

        if (Auth::user()->role_id == 1) {
            $lastid = Mualaf::create([
                'users_id' => $request->users_id,
                'jml_mualaf' => $request->jml_mualaf,
                'tgl' => $request->tgl,
                'date' => $date,
                'month' => $month,
                'year' => $year
            ])->id;
        } else {
            $lastid = Mualaf::create([
                'users_id' => Auth::user()->id,
                'jml_mualaf' => $request->jml_mualaf,
                'tgl' => $request->tgl,
                'date' => $date,
                'month' => $month,
                'year' => $year
            ])->id;
        }

        $this->validate($request, [
            'foto' => 'required',
            'foto.*' => 'mimes:jpeg,jpg,png|max:2000',
            'nama' => 'required',
            'alamat' => 'required',
            'deskripsi' => 'required'
        ]);

        if (count($request->file('foto')) > 0) {
            foreach ($request->file('foto') as $item => $v) {
                $datad = array(
                    'mualafs_id' => $lastid,
                    'nama' => $request->nama[$item],
                    'alamat' => $request->alamat[$item],
                    'deskripsi' => $request->deskripsi[$item],
                    'foto' => $v->getClientOriginalName()
                );
                $v->storeAs('public/mualaf', $v->getClientOriginalName());
                MualafDetail::insert($datad);
            }
        }

        session()->flash('sukses', 'Data berhasil di Input');
        return redirect('/mualafs');
    }
}

resources/views/pages/cms/mualaf/edit.blade.php
@extends('layouts.admin')
@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">
        <!-- Content Row -->
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="mt-12 row">
            <div class="col md-5">
                <div class="card-deck">
                    <div class="mb-5 col-xl-12 col-md-8">
                        <div class="py-2 shadow card border-left-primary h-100">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="modal-body">
                                        <h3 class="mb-4 text-gray-800 h3">Edit Data</h3>
                                        <hr>
                                        <form method="POST" action="{{ route('mualafs.update', $mualaf->id) }}" enctype="multipart/form-data">
                                            @method('PUT')
                                            @csrf
                                            <div class="form-group row">
                                                <label for="tgl" class="col-sm-2 col-form-label">Tanggal</label>
                                                <div class="col-sm-10">
                                                    <input id="tgl" type="text"
                                                        class="form-control datepicker @error('tgl') is-invalid @enderror"
                                                        name="tgl" value="{{ old('tgl', $mualaf->tgl) }}"
                                                        autocomplete="tgl" autofocus>
                                                    @error('tgl')
                                                        <span class="invalid-feedback" role="alert">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                                    @enderror
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label for="jml_mualaf" class="col-sm-2 col-form-label">Jumlah
                                                    Mualaf</label>
                                                <div class="col-sm-10">
                                                    <input id="jml_mualaf" type="number" class="form-control"
                                                        name="jml_mualaf"
                                                        value="{{ old('jml_mualaf', $mualaf->jml_mualaf) }}"
                                                        autocomplete="jml_mualaf" autofocus>
                                                    @error('jml_mualaf')
                                                        <span class="invalid-feedback" role="alert">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                                    @enderror
                                                </div>
                                            </div>
                                            <hr>
                                            <div class="form-group row">
                                                <div class="col-sm-2">
                                                    <h6>Data Mualaf</h6>
                                                </div>
                                                <div class="col-sm-10">
                                                    @foreach ($mualaf->fotos as $detail)
                                                    <input type="hidden" name="id[]" value="{{$detail->id}}">
                                                    <div class="mt-4 card">
                                                        <div class="card-body">
                                                            <div class="form-group row">
                                                                <div class="mt-2 col-md-6">
                                                                    <label>Nama Mualaf</label>
                                                                    <div class="input-group realprocode control-group lst increment">
                                                                        <div class="custom-file">
                                                                            <input type="text" name="nama[]" class="form-control" id="nama"
                                                                                placeholder="Nama" value="{{ old('nama', $detail->nama) }}"/>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div class="mt-2 col-md-6 form-group">
                                                                    <label>Alamat</label>
                                                                    <input type="text" required class="form-control" name="alamat[]" id="alamat"
                                                                        placeholder="Alamat" data-rule="alamat"
                                                                        data-msg="Please enter a valid alamat" value="{{  old('alamat', $detail->alamat) }}"/>
                                                                    <div class="validate"></div>
                                                                </div>
                                                            </div>
                                                            <div class="form-group row">
                                                                <div class="col-md-4 form-group">
                                                                    <label>Foto Dokumentasi</label>
                                                                    <div class="form-group">
                                                                        <input type="file" name="foto[]" class="form-control-file"
                                                            id="exampleFormControlFile1" value="{{ $detail->foto }}"><br>
                                                                        <div class="form-group">
                                                                            <img src="{{ Storage::url('mualaf/' . $detail->foto) }}" class="img-thumbnail" width="50%">
                                                                            <p>{{ $detail->foto }}</p>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div class="col-md-8 form-group">
                                                                    <label>Ceritakan Bagaimana Mengenal Islam</label>
                                                                    <textarea class="form-control" name="deskripsi[]" required="required" rows="6"
                                                                        value="{{ old('deskripsi', $detail->deskripsi) }}">{{ $detail->deskripsi }}</textarea>
                                                                    @error('deskripsi')
                                                                        <span class="invalid-feedback" role="alert">
                                                                            <strong>{{ $message }}</strong>
                                                                        </span>
                                                                    @enderror
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    @endforeach
                                                </div>
                                            </div>
                                            <div class="form-file row justify-content-end">
                                                <div class="col-sm-10">
                                                    <button type="submit" class="btn btn-primary btn-block">Simpan</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
@endsection

resources/views/pages/cms/mualaf/export_excel.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
</head>

<body>
    <table>
        <thead>
            <tr>
                <th style="text-align: right;" rowspan="4"></th>
                <th valign="center" colspan="4"
                    style="font-weight: bold; text-align: center; border: 2px solid #ffffff;">YAYASAN BAITUL MAAL </th>
            </tr>
            <tr>
                <th valign="center" colspan="4"
                    style="font-weight: bold; text-align: center; border: 2px solid #ffffff;">PLN WILAYAH KALIMANTAN
                    BARAT</th>
            </tr>
            <tr>
                <th valign="center" colspan="4"
                    style="font-weight: bold; text-align: center; border: 2px solid #ffffff;">Jalan Adisucipto Km 7,3
                    Sei Raya</th>
            </tr>
            <tr>
                <th valign="center" colspan="4"
                    style="font-weight: bold; text-align: center; border: 2px solid #ffffff;">KABUPATEN KUBU RAYA
                </th>
            </tr>
            <tr>
                <td style="border: 2px solid #ffffff;"></td>
                <td style="border: 2px solid #ffffff;"></td>
                <td style="border: 2px solid #ffffff;"></td>
                <td style="border: 2px solid #ffffff;"></td>
                <td style="border: 2px solid #ffffff;"></td>
            </tr>
            <tr>
                <th style="width: 20px; font-weight: bold; border: 2px solid #000000; text-align: center;">Nama Ustadz
                </th>
                <th style="width: 20px; font-weight: bold; border: 2px solid #000000; text-align: center;">Tanggal</th>
                <th style="width: 20px; font-weight: bold; border: 2px solid #000000; text-align: center;">Jumlah Mualaf
                </th>
                <th style="width: 20px; font-weight: bold; border: 2px solid #000000; text-align: center;">Alamat
                </th>
                <th style="width: 20px; font-weight: bold; border: 2px solid #000000; text-align: center;">Deskripsi
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach ($export_excel as $mualaf)
                <tr>
                    <td style="border: 2px solid #000000;">{{ $mualaf->user->username }}</td>
                    <td style="border: 2px solid #000000;">{{ $mualaf->tgl }}</td>
                    <td style="border: 2px solid #000000;">{{ $mualaf->jml_mualaf }}</td>
                    <td style="border: 2px solid #000000;">{{ $mualaf->user->alamat }}</td>
                    <td style="border: 2px solid #000000; width:50px;">{{ $mualaf->deskripsi }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

</body>

</html>

resources/views/pages/cms/mualaf/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container-fluid">
        @if (session()->has('sukses'))
            <div class="alert alert-info col-xl-12 alert-dismissible fade show" role="alert">
                {{ session()->get('sukses') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
        <div class="card border-left-primary shadow mb-4">
            <div class="card-header py-3">
                <div class="d-sm-flex align-items-center justify-content-between">
                    <h5 class="m-0 font-weight-bold text-gray-800 mt-2">Data Mualaf</h5>
                    @if (Auth::user()->role_id == 1)
                        <a href="{{ url('/mualaf') }}" class="btn btn-sm btn-primary mt-2"
                            style="color: #fff; margin-left: auto;"><i class="fas fa-plus"></i>
                            &nbsp;Tambah</a>&nbsp;
                        <a href="{{ url('/mualaf/export-excel') }}" class="btn btn-sm btn-success btn-export mt-2"
                            style="color: #fff"><i class="far fa-file-excel"></i>
                            &nbsp;Export Excel</a>
                    @else
                        <a href="{{ url('/mualaf') }}" class="btn btn-sm btn-primary mt-2"
                                style="color: #fff; margin-left: auto;"><i class="fas fa-plus"></i>
                                &nbsp;Tambah</a>
                    @endif
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Nama Ustadz</th>
                                <th>Tanggal</th>
                                <th>Jum Mualaf</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php $no = 1; @endphp
                            @forelse($items as $item)
                                <tr>
                                    <td>{{ $no++ }}</td>
                                    <td>{{ $item->user->username }}</td>
                                    <td>{{ $item->tgl }}</td>
                                    <td>{{ $item->jml_mualaf }}</td>
                                    <td>
                                        <a href="{{ route('mualafs.show', $item->id) }}" class="btn btn-sm btn-primary">
                                            <i class="fa fa-search-plus"></i>
                                        </a>
                                        @if (Auth::user()->role_id == 1)
                                            <a href="{{ route('mualafs.edit', $item->id) }}" class="btn btn-sm btn-info">
                                                <i class="fa fa-pencil-alt"></i>
                                            </a>
                                            {{-- <form action="{{ route('mualafs.destroy', $item->id) }}" method="post"
                                                class="d-inline">
                                                @csrf
                                                @method('delete')
                                                <button class="btn btn-sm btn-danger">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            </form> --}}
                                            <form method="POST" action="{{ route('mualafs.destroy', $item->id) }}" class="d-inline">
                                                @csrf
                                                @method('delete')
                                                <input name="_method" type="hidden" value="DELETE">
                                                <button type="submit" class="btn btn-sm btn-danger btn-flat show_confirm" data-toggle="tooltip" title='Delete'><i class="fa fa-trash"></i></button>
                                            </form>
                                        @else
                                        @endif
                                    </td>
                                </tr>
                            @empty
                                <td colspan="7" class="text-center">
                                    Data Kosong
                                </td>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
@endsection