routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// public
Route::get('/', 'HomeController@index')
    ->name('home');
Route::get('/profiles', 'MenuController@profiles')
    ->name('profiles');
Route::get('/berita', 'MenuController@berita')
    ->name('berita');
Route::get('/berita/ustyanto', 'MenuController@ustyanto')
    ->name('detail.ustyanto');
Route::get('/berita/beting-to-bening', 'MenuController@beting_to_bening')
    ->name('detail.beting_to_bening');
Route::get('/berita/training-imam-dan-khatib', 'MenuController@training_imam_dan_khatib')
    ->name('detail.training_imam_dan_khatib');
Route::get('/gambar', 'MenuController@gambar')
    ->name('gambar');
Route::get('/kontak', 'MenuController@kontak')
    ->name('kontak');
Route::post('/kontak/store', 'MenuController@store');
Route::post('/kontak/stores', 'MenuController@stores');

// admin & dai
Route::group(['middleware' => 'auth'], function () {

    Route::get('/kegiatan', 'KegiatanController@input')
        ->name('kegiatan_input');;

    Route::post('/kegiatan/store', 'KegiatanController@store');

    Route::get('kegiatan/export-excel/', 'KegiatanController@export_excel');

    Route::resource(
        'kegiatans',
        'KegiatanController',
        ['except' => ['create']]
    );

    Route::get('/mualaf', 'MualafController@input')
        ->name('mualaf');

    Route::post('/mualaf/create', 'MualafController@create');

    Route::resource(
        'mualafs',
        'MualafController',
        ['except' => ['create']]
    );

    Route::get('mualaf/export-excel/', 'MualafController@export_excel');

    Route::get('/getDistricts/{id}', 'KegiatanController@getDistricts');

    Route::get('/getVillages/{id}', 'KegiatanController@getVillages');

    Route::get('/profile', 'ProfileController@edit')
        ->name('profile.edit');

    Route::patch('/profile', 'ProfileController@update')
        ->name('profile.update');

    Route::get('password', 'PasswordController@edit')
        ->name('user.password.edit');

    Route::patch('password', 'PasswordController@update')
        ->name('user.password.update');

    Route::get('dashboard', 'DashboardController@index')
        ->name('dashboard.index');
});

// admin
Route::prefix('admin')
    ->namespace('Admin')
    ->middleware(['auth', 'admin'])
    ->group(function () {
        Route::resource('users', 'UsersController');
        Route::resource('pesan', 'PesanController');
        Route::get('dai', 'UsersController@dai')
            ->name('dai.index');

        Route::get('/dai/create-dai', 'UsersController@create_dai')
            ->name('dai.create_dai');;
        Route::post('/dai/store-dai', 'UsersController@store_dai')->name('dai.store_dai');

        Route::get('/dai/{user}/ubah', 'UsersController@ubah')->name('dai.ubah');
        Route::put('/dai/simpan/{user}', 'UsersController@simpan')->name('dai.simpan');
        Route::get('/dai/detail/{user}', 'UsersController@detail')->name('dai.detail');
        Route::delete('/dai/delete/{user}', 'UsersController@delete')->name('dai.delete');

        Route::resource('role', 'RoleController');
    });

Auth::routes(['verify' => true]);

resources/views/includes/admin/footer.blade.php
<!-- Footer -->
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; YBM PLN Kalimantan Barat <?= date('Y') ?></span>
    </div>
  </div>
</footer>

resources/views/includes/admin/navbar.blade.php
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">
                    {{ Auth::user()->username }}
                </span>
                <img class="img-profile rounded-circle"
                    src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/OOjs_UI_icon_userAvatar.svg/1200px-OOjs_UI_icon_userAvatar.svg.png">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                @can('manage-users')
                    <a class="dropdown-item" href="{{ route('users.index') }}">
                        <i class="fas fa-users fa-sm fa-fw mr-2 text-gray-400"></i>
                        User Management
                    </a>
                @endcan
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Keluar
                </a>
            </div>
        </li>

    </ul>

</nav>
<!-- End of Topbar -->

resources/views/includes/admin/script.blade.php
<script src="{{ url('backend/vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ url('backend/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ url('backend/vendor/jquery-easing/jquery.easing.min.js') }}"></script>
<script src="{{ url('backend/js/sb-admin-2.min.js') }}"></script>

<script src="{{ url('backend/vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ url('backend/vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ url('backend/js/demo/datatables-demo.js') }}"></script>

<script src="{{ url('backend/vendor/chart.js/Chart.min.js') }}"></script>

<script src="{{ url('backend/js/demo/chart-area-demo.js') }}"></script>
<script src="{{ url('backend/js/demo/chart-pie-demo.js') }}"></script>
<script src="{{ url('backend/js/demo/chart-bar-demo.js') }}"></script>
<script src="{{ url('backend/js/demo/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
    <script type="text/javascript">

        $('.show_confirm').click(function(event) {
            var form =  $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                title: `Apakah Anda Yaqin?`,
                text: "Data yang sudah dihapus tidak dapat dikembalikan.",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
                if (willDelete) {
                    form.submit();
                }
            });
        });

    </script>

<script>
    $('select').selectpicker();

</script>

<script>
    $(function() {
        $('#only-number').on('keydown', '#nohp', function(e) {
            -1 !== $
                .inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) || /65|67|86|88/
                .test(e.keyCode) && (!0 === e.ctrlKey || !0 === e.metaKey) ||
                35 <= e.keyCode && 40 >= e.keyCode || (e.shiftKey || 48 > e.keyCode || 57 < e
                    .keyCode) &&
                (96 > e.keyCode || 105 < e.keyCode) && e.preventDefault()
        });
    });

    $(document).ready(function() {
        $("#show_hide_password a").on('click', function(event) {
            event.preventDefault();
            if ($('#show_hide_password input').attr("type") == "text") {
                $('#show_hide_password input').attr('type', 'password');
                $('#show_hide_password i').addClass("fa-eye-slash");
                $('#show_hide_password i').removeClass("fa-eye");
            } else if ($('#show_hide_password input').attr("type") == "password") {
                $('#show_hide_password input').attr('type', 'text');
                $('#show_hide_password i').removeClass("fa-eye-slash");
                $('#show_hide_password i').addClass("fa-eye");
            }
        });
    });

    $(document).ready(function() {
        $("#show_hide_passwordd a").on('click', function(event) {
            event.preventDefault();
            if ($('#show_hide_passwordd input').attr("type") == "text") {
                $('#show_hide_passwordd input').attr('type', 'password');
                $('#show_hide_passwordd i').addClass("fa-eye-slash");
                $('#show_hide_passwordd i').removeClass("fa-eye");
            } else if ($('#show_hide_passwordd input').attr("type") == "password") {
                $('#show_hide_passwordd input').attr('type', 'text');
                $('#show_hide_passwordd i').removeClass("fa-eye-slash");
                $('#show_hide_passwordd i').addClass("fa-eye");
            }
        });
    });

    $(document).ready(function() {
        $("#show_hide_password_login a").on('click', function(event) {
            event.preventDefault();
            if ($('#show_hide_password_login input').attr("type") == "text") {
                $('#show_hide_password_login input').attr('type', 'password');
                $('#show_hide_password_login i').addClass("fa-eye-slash");
                $('#show_hide_password_login i').removeClass("fa-eye");
            } else if ($('#show_hide_password_login input').attr("type") == "password") {
                $('#show_hide_password_login input').attr('type', 'text');
                $('#show_hide_password_login i').removeClass("fa-eye-slash");
                $('#show_hide_password_login i').addClass("fa-eye");
            }
        });
    });

</script>

<script>
    $(document).ready(function() {
        $('.datepicker').datepicker({
            format: 'dd/mm/yyyy',
            autoclose: true,
            todayHighlight: true,
        });
    });

</script>

resources/views/includes/admin/sidebar.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ route('home') }}">
        <div class="sidebar-brand-icon">
            @if (Auth::user()->role_id == 1)
                    Admin
            @else
                Dai
            @endif
        </div>
        <div class="sidebar-brand-text mx-1">
            YBM PLN
        </div>
    </a>

    <hr class="sidebar-divider my-0">
    <li class="nav-item">
        <a class="nav-link" href="{{ route('dashboard.index') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>
    @if (Auth::user()->role_id == 1)
        <hr class="sidebar-divider">

        <li class="nav-item">
            <a class="nav-link" href="{{ route('kegiatans.index') }}">
                <i class="fas fa-fw fa-chart-area"></i>
                <span>Data Kegiatan Dai</span></a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{{ route('mualafs.index') }}">
                <i class="fas fa-fw fa-chart-area"></i>
                <span>Data Mualaf</span></a>
        </li>

        <hr class="sidebar-divider">

        <div class="sidebar-heading">
            Admin
        </div>
        <li class="nav-item">
            <a class="nav-link" href="{{ route('pesan.index') }}">
                <i class="fas fa-fw fa-envelope"></i>
                <span>Pesan Masuk</span></a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{{ route('dai.index') }}">
                <i class="fas fa-fw fa-users"></i>
                <span>Data Dai</span></a>
        </li>

        <!-- Nav Item - Charts -->
        <li class="nav-item">
            <a class="nav-link" href="{{ route('role.index') }}">
                <i class=" fas fa-fw fa-user"></i>
                <span>Role</span></a>
        </li>

        <!-- Nav Item - Tables -->
        <li class="nav-item">
            <a class="nav-link" href="{{ route('users.index') }}">
                <i class="fas fa-fw fa-users"></i>
                <span>Users</span></a>
        </li>
    @elseif (Auth::user()->role_id == 2)
        <li class="nav-item">
            <a class="nav-link" href="{{ route('kegiatans.index') }}">
                <i class="fas fa-fw fa-chart-area"></i>
                <span>Data Kegiatan Dai</span></a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{{ route('mualafs.index') }}">
                <i class="fas fa-fw fa-chart-area"></i>
                <span>Data Mualaf</span></a>
        </li>
    @elseif (Auth::user()->role_id == 3)

    @else
    @endif
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true"
            aria-controls="collapsePages">
            <i class="fas fa-fw fa-user"></i>
            <span>Profile</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Profile:</h6>
                <a class="collapse-item" href="{{ route('profile.edit') }}">Profile</a>
                <a class="collapse-item" href="{{ route('user.password.edit') }}">Edit Password</a>
            </div>
        </div>
    </li>

    <hr class="sidebar-divider d-none d-md-block">

    <li class="nav-item">
        <a class="nav-link" href="#" data-toggle="modal" data-target="#logoutModal">
            <i class="fas fa-fw fa-sign-out-alt"></i>
            <span>Keluar</span>
        </a>
    </li>

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
<!-- End of Sidebar -->

resources/views/includes/admin/style.blade.php
<!-- Favicons -->
<link href="{{ url('fronten/assets/img/favicon.ico') }}" rel="icon">
<link href="{{ url('fronten/assets/img/apple-touch-icon.png') }}" rel="apple-touch-icon">
<!-- Custom fonts for this template-->
<link href="{{ url('backend/vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
<link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

<!-- Custom styles for this template-->
<link href="{{ url('backend/css/sb-admin-2.min.css') }}" rel="stylesheet">
<link rel="stylesheet" href="{{ url('backend/css/style.css') }}">
<link rel="stylesheet" href="{{ url('backend/vendor/datatables/dataTables.bootstrap4.min.css') }}">
<link href="{{ url('fronten/assets/vendor/bootstrap-datepicker/css/bootstrap-datepicker.min.css') }}"
    rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />