routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// public
Route::get('/', 'HomeController@index')
    ->name('home');
Route::get('/profiles', 'MenuController@profiles')
    ->name('profiles');
Route::get('/berita', 'MenuController@berita')
    ->name('berita');
Route::get('/berita/ustyanto', 'MenuController@ustyanto')
    ->name('detail.ustyanto');
Route::get('/berita/beting-to-bening', 'MenuController@beting_to_bening')
    ->name('detail.beting_to_bening');
Route::get('/berita/training-imam-dan-khatib', 'MenuController@training_imam_dan_khatib')
    ->name('detail.training_imam_dan_khatib');
Route::get('/gambar', 'MenuController@gambar')
    ->name('gambar');
Route::get('/kontak', 'MenuController@kontak')
    ->name('kontak');
Route::post('/kontak/store', 'MenuController@store');
Route::post('/kontak/stores', 'MenuController@stores');

// admin & dai
Route::group(['middleware' => 'auth'], function () {

    Route::get('/kegiatan', 'KegiatanController@input')
        ->name('kegiatan_input');;

    Route::post('/kegiatan/store', 'KegiatanController@store');

    Route::get('kegiatan/export-excel/', 'KegiatanController@export_excel');

    Route::resource(
        'kegiatans',
        'KegiatanController',
        ['except' => ['create']]
    );

    Route::get('/mualaf', 'MualafController@input')
        ->name('mualaf');

    Route::post('/mualaf/create', 'MualafController@create');

    Route::resource(
        'mualafs',
        'MualafController',
        ['except' => ['create']]
    );

    Route::get('mualaf/export-excel/', 'MualafController@export_excel');

    Route::get('/getDistricts/{id}', 'KegiatanController@getDistricts');

    Route::get('/getVillages/{id}', 'KegiatanController@getVillages');

    Route::get('/profile', 'ProfileController@edit')
        ->name('profile.edit');

    Route::patch('/profile', 'ProfileController@update')
        ->name('profile.update');

    Route::get('password', 'PasswordController@edit')
        ->name('user.password.edit');

    Route::patch('password', 'PasswordController@update')
        ->name('user.password.update');

    Route::get('dashboard', 'DashboardController@index')
        ->name('dashboard.index');
});

// admin
Route::prefix('admin')
    ->namespace('Admin')
    ->middleware(['auth', 'admin'])
    ->group(function () {
        Route::resource('users', 'UsersController');
        Route::resource('pesan', 'PesanController');
        Route::get('dai', 'UsersController@dai')
            ->name('dai.index');

        Route::get('/dai/create-dai', 'UsersController@create_dai')
            ->name('dai.create_dai');;
        Route::post('/dai/store-dai', 'UsersController@store_dai')->name('dai.store_dai');

        Route::get('/dai/{user}/ubah', 'UsersController@ubah')->name('dai.ubah');
        Route::put('/dai/simpan/{user}', 'UsersController@simpan')->name('dai.simpan');
        Route::get('/dai/detail/{user}', 'UsersController@detail')->name('dai.detail');
        Route::delete('/dai/delete/{user}', 'UsersController@delete')->name('dai.delete');

        Route::resource('role', 'RoleController');
    });

Auth::routes(['verify' => true]);

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    public function users()
    {
        return $this->belongsToMany('App\User');
    }

    protected $fillable = ['name'];

    public function userss()
    {
        return $this->hasMany(User::class, 'role_id', 'id');
    }
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\RoleRequest;
use App\Role;
use Illuminate\Support\Str;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::all();

        return view('pages.admin.role.index', [
            'roles' => $roles
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    // public function create()
    // {
    //     return view('pages.admin.role.create');
    // }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    // public function store(RoleRequest $request)
    // {
    //     Role::create([
    //         'name' => $request->name,
    //     ]);
    //     session()->flash('sukses', 'Data Role berhasil ditambahkan');
    //     return redirect(route('role.index'));
    // }

    // public function edit(Role $role)
    // {
    //     return view('pages.admin.role.edit')->withRole($role);
    // }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    // public function update(RoleRequest $request, Role $role)
    // {
    //     $role->update([
    //         'name' => $request->name
    //     ]);
    //     session()->flash('sukses', 'Role berhasil di Ubah');
    //     return redirect(route('role.index'));
    // }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    // public function destroy(Role $role)
    // {
    //     $role->delete();
    //     session()->flash('sukses', 'Role berhasil di Hapus');
    //     return redirect(route('role.index'));
    // }
}

resources/views/pages/admin/role/create.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">
        <!-- Content Row -->
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <div class="row mt-12">
            <div class="col md-5">
                <div class="card-deck">
                    <div class="col-xl-12 col-md-8 mb-5">
                        <div class="card border-left-warning shadow h-100 py-2">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="modal-body">
                                        <h3 class="h3 mb-4 text-gray-800">
                                            Tambah Role
                                        </h3>
                                        <hr>
                                        <form action="{{ route('role.store') }}" method="post">
                                            @csrf
                                            <div class="form-group">
                                                <input type="text" class="form-control" name="name" placeholder="Role"
                                                    value="{{ old('name') }}">
                                            </div>
                                            <button type="submit" class="btn admin-login btn-user btn-block admin-btn">
                                                Simpan
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
@endsection

resources/views/pages/admin/role/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container-fluid">
        <div class="card border-left-primary shadow mb-4">
            <div class="card-header py-3">
                <div class="d-sm-flex align-items-center justify-content-between">
                    <h5 class="h3 mb-0 text-gray-800">Edit User {{ $role->name }}</h5>
                </div>
            </div>
            <div class="card-body">
                <form action="{{ isset($role) ? route('role.update', $role->id) : route('role.store') }}" method="POST">
                    @csrf
                    @if (isset($role))
                        @method('PATCH')
                    @endif
                    <div class="form-group">
                        <input type="text" class="form-control" id="name" name="name" required autocomplete="name"
                            placeholder="Role" autofocus value="{{ isset($role) ? $role->name : old('name') }}">
                    </div>
                    <button type=" submit" class="btn btn-primary btn-block">Simpan</button>
                </form>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
@endsection

resources/views/pages/admin/role/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container-fluid">
        <div class="card border-left-primary shadow mb-4">
            @if (session()->has('sukses'))
                <div class="alert alert-info col-xl-12 alert-dismissible fade show" role="alert">
                    {{ session()->get('sukses') }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif
            {{-- <div class="d-sm-flex align-items-center justify-content-between mb-4">
                                        <h3 class="h3 mb-0 text-gray-800">Roles</h3>
                                        <a href="{{ route('role.create') }}"
                                            class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
                                            <i class="fas fa-plus fa-sm text-white-50"></i> Tambah Role
                                        </a>
            </div> --}}
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th scope="col">No</th>
                                <th scope="col">Role</th>
                                {{-- <th scope="col">Action</th> --}}
                            </tr>
                        </thead>
                        <tbody>
                            @php $no = 1; @endphp
                            @forelse($roles as $item)
                                <tr>
                                    <td>{{ $no++ }}</td>
                                    <td>{{ $item->name }}</td>
                                    {{-- <td>
                                        <a href="{{ route('role.edit', $item->id) }}" class="btn btn-sm btn-info">
                                            <i class="fa fa-pencil-alt"></i>
                                        </a>
                                        <form action="{{ route('role.destroy', $item->id) }}" method="post"
                                            class="d-inline">
                                            @csrf
                                            @method('delete')
                                            <button class="btn btn-danger btn-sm">
                                                <i class="fa fa-trash"></i>
                                            </button>
                                        </form>
                                    </td> --}}
                                </tr>
                            @empty
                                <td colspan="7" class="text-center">
                                    Data Kosong
                                </td>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
@endsection